### ISSUE TITLE
Master Plan

### ISSUE THREAD

**Issue by tholoien** [tholoien/empiriciSN#8]
This is a basic roadmap for the tasks that need to be completed. It will be updated to link to sub-issues and to mark progress.
- [x] Gather SN and host data for the SDSS and SNLS samples
  - [x] Change SNLS parameters from SALT to SALT2 (#7)
  - [x] Change K-correction to use kcorrect (#14)
- [x] Sort data and calculate quantities to be used in the modeling, remake master data files (#4, #9)
- [x] Make plots comparing the various SN and host parameters (#10)
- [x] Perform XD modeling  (#11)
- [x] Build XDGMM wrapper class that can be used with scikit-learn machine learning methods (#15)
- [x] Train the model and use cross-validation to find best number of parameters and estimate the model's reliability (#12)
- [x] Build a simple tool to be used to generate supernova light curves based on the model given CatSim parameters (#13)

**Comment by tholoien** [comment]
Everything is up and running!
